name: "Version2"

on:
  push:
    branches:
      - master

jobs:
  stage1: 
    runs-on: ubuntu-latest
    steps:
      - name: Files before checkout
        run: ls -la

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Files after checkout
        run: ls -la

      - name: Read original file
        run: cat original.txt
